### ISSUE TITLE
Allow for separate translations of a job posting

### ISSUE THREAD

**Issue by ConcernedHobbit** [TKOaly/job-board-next#13]
Related to #4.

When creating a job posting, it should be possible to add translations for different languages.

On the main page, job postings should be presented based on the user's language preference first, falling back in order `English->Finnish->other languages present for the job posting`.

On the job posting detail page, it should be possible to switch between languages (and see which translations are available). This should be clearly separate from #7 indicators, so users are not confused about the working language of the job posting.

**Comment by dogamak** [comment]
Implemented with the distinction that only languages Finnish, English and "Unknown" are supported. All old text is by default of language "Unknown". The order of preference for languages is `[currentLanguage,"en","fi","xx"]`, where `xx` is unknown.

The main reason for only supporting these languages was that supporting arbitrary languages would complicate the administration UI in order to support a case that we might have yet to encounter after 7 years of running the site.

The translation feature can be seen in action [on this post](https://jobs.tko-aly.fi/fi/posts/704) among others.
